# Generated by Django 5.0.3 on 2024-03-18 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infotech', '0003_rename_projects_project_client_project_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='client',
            new_name='projects',
        ),
        migrations.RemoveField(
            model_name='project',
            name='users',
        ),
    ]
